In [0]:
import numpy as np

We want to represent an animal using numpy, a panda for exemple. Let's take a numpy.array to represent some of his caracteristics:

[paws length,hair length,tale's length,diameter]

In [0]:
a_numpy_panda = np.array([100,5,20,80])
a_numpy_panda

array([100,   5,  20,  80])

So if I want multiple pandas i represent a list of pandas:

In [0]:
panda_family = [
                np.array([100,5,20,80]), #momy panda
                np.array([50,2.4,9,40]), #baby panda
                np.array([110,5,22,83]) #dady panda
]
panda_family

[array([100,   5,  20,  80]),
 array([50. ,  2.4,  9. , 40. ]),
 array([110,   5,  22,  83])]

We can do better with numpy arrays ;)

In [0]:
np_panda_family = np.array([
                    [100,5,20,80], #momy panda
                    [50,2.4,9,40], #baby panda
                    [110,5,22,83], #dady panda
])
np_panda_family

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.4,   9. ,  40. ],
       [110. ,   5. ,  22. ,  83. ]])

In [0]:
#or we can do this
np_panda_family2 = np.array(panda_family)
print(np_panda_family2)

[[100.    5.   20.   80. ]
 [ 50.    2.4   9.   40. ]
 [110.    5.   22.   83. ]]


So we have an array of arrays
or a 2dim array (shape == (3,4))

In [0]:
#if we want the hair lenggth of the baby:
print("baby panda's hair length: {}".format(np_panda_family[1,1]))

#if we want to now the hair length of every memeber:
print("the hair lengths: {}".format(np_panda_family[:,1]))

baby panda's hair length: 2.4
the hair lengths: [5.  2.4 2.4]


As we just saw, we can represent tables of informations or commonly called dataframes with numpy. But it.s not intuitive neither explicit, indeed we cannot now what each column represent as informations without having an external reference.
So we have to look for another solution to have a better representation of our data.
Actually python gives us a library which we can make a good use of, it's called Pandas, yeah like the cute asian bear lol.

# Panda library (panel date)
It's a python library used to manipulate numerical tables but it's particularity is that we can add indexes to the ligne and colmns.


In [0]:
# Importing the pandas library
import pandas as pd

The object that will let us manipulate data are called DataFrames and it's created by giving it an array of dim == 2 (an array of arrays)

In [0]:
# Transforming the np_panda_family into a dataframe
df_panda_family = pd.DataFrame(np_panda_family)
print(df_panda_family)

       0    1     2     3
0  100.0  5.0  20.0  80.0
1   50.0  2.4   9.0  40.0
2   50.0  2.4   9.0  40.0


So this is the DataFrame of the panda family

We notice that there is two new rows, a vertical and an horizontal one. Thos two are the indexes

But we want to refere to each column as her name. Easy, we will just add array of the indexes and the array of the columns as parameters in the method pd.DataFrame


In [0]:
# creating an explicit DataFrame
df_panda_family = pd.DataFrame(np_panda_family2,
                               columns=["paws","hair","tale","diameter"],
                               index=["momy","baby","dady"])
df_panda_family

paws  hair  tale  diameter
momy  100.0   5.0  20.0      80.0
baby   50.0   2.4   9.0      40.0
dady  110.0   5.0  22.0      83.0

So the cool thing about pandas is that it uses numpy's properties. So we can guess tha it uses a Vstack([columns,table]) and an Hstack([index,table])
so as in numpy we have to respect the shape of the tables.

# DataFrames functionalities:

In [0]:
df = df_panda_family #just to simplify cuz am lazy
# how to access to columns(two ways):
df["tale"]
df.tale


momy    20.0
baby     9.0
dady    22.0
Name: tale, dtype: float64

The returned object by ```df.tale``` is a 'panda.Series' to get the numpy array format we use ```df.tale.values``` 

In [0]:
print(type(df.tale))
print(type(df.tale.values))
df.tale.values

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


array([20.,  9., 22.])

This is how to access rows

In [0]:
# again, two methodes
# 1st
df.loc["dady"]

paws        110.0
hair          5.0
tale         22.0
diameter     83.0
Name: dady, dtype: float64

In [0]:
# 2nd
df.iloc[1] # iloc uses the positional indexing so you have to know the position of the row you're looking for

paws        50.0
hair         2.4
tale         9.0
diameter    40.0
Name: baby, dtype: float64

In [0]:
# yes we can do slicing on DataFrames
df.iloc[:2]

paws  hair  tale  diameter
momy  100.0   5.0  20.0      80.0
baby   50.0   2.4   9.0      40.0

The python fexibility lets us irterate easily on DataFrames using ```.iterrows()```

The method returns a tuple with the index of the row in the first position and the row itself in the second position

In [0]:
for index, line in df.iterrows():
  print("The panda member: {}".format(index))
  print(line,end="\n--------------------\n")

The panda member: momy
paws        100.0
hair          5.0
tale         20.0
diameter     80.0
Name: momy, dtype: float64
--------------------
The panda member: baby
paws        50.0
hair         2.4
tale         9.0
diameter    40.0
Name: baby, dtype: float64
--------------------
The panda member: dady
paws        110.0
hair          5.0
tale         22.0
diameter     83.0
Name: dady, dtype: float64
--------------------


In [0]:
# to remind us of tuple
for x in df.iterrows():
  print(x[0])
  print(x[1], end="\n--------------------\n")
# will print the same thing

In [0]:
# let's try something
df.diameter >= 80

momy     True
baby    False
dady     True
Name: diameter, dtype: bool

Python will compare each value of the clumn to the value.
it remind us of something huh ?

Yeaaah ! It's the boolean indexation of numpy, let's see what we can do

In [0]:
# it work like the network masks
mask = df.diameter >= 80
print (mask)
df[mask]

momy     True
baby    False
dady     True
Name: diameter, dtype: bool


paws  hair  tale  diameter
momy  100.0   5.0  20.0      80.0
dady  110.0   5.0  22.0      83.0

Python will print only the rows that validate the condition (which is the diameter should be >= 80)

In [0]:
# We also can use it directly this way
df[df.diameter >= 80]

paws  hair  tale  diameter
momy  100.0   5.0  20.0      80.0
dady  110.0   5.0  22.0      83.0

In [0]:
# We can invert the mask if we don't want to write the negation
df[~mask]

paws  hair  tale  diameter
baby  50.0   2.4   9.0      40.0

# Expanding the DataFrame

It wouldn't be interresting if we had to work on only data frame, what if we wanted to add some rows in it

In [0]:
# putting the data in a new DataFrame
other_pandas = pd.DataFrame(np.array([[80,4,15,65],
                                      [200,8,30,100],
                                      [100,5,20,80]]),
                            columns = df.columns,
                            index = ["son","giant","other"]) # don't forget to add the columns for the compatibility
newDf = df.append(other_pandas) # just like we do to add values in a liste except that we have to save the DataFrame in a new one
newDf

paws  hair  tale  diameter
momy   100.0   5.0  20.0      80.0
baby    50.0   2.4   9.0      40.0
dady   110.0   5.0  22.0      83.0
son     80.0   4.0  15.0      65.0
giant  200.0   8.0  30.0     100.0
other  100.0   5.0  20.0      80.0

In [0]:
#  but we don't want duplacation in our DataFrame. Not a problem
newDf = newDf.drop_duplicates()
newDf

paws  hair  tale  diameter
momy   100.0   5.0  20.0      80.0
baby    50.0   2.4   9.0      40.0
dady   110.0   5.0  22.0      83.0
son     80.0   4.0  15.0      65.0
giant  200.0   8.0  30.0     100.0

As written in the comments, appending the DataFrame will not modify it, it will create a new DataFrame.

So if we want to keep it we can put the returned data frame in a new variable or, -if we don't  need the old one- we can replace it with the new one: ```old_dataFrame = old_dataFrame.append(another_dataFrame)```

# Adding a new column

In [0]:
newDf["sexe"] = ["f","f","m","m","m"] # we have to add a list with a length equal to the number of the rows
newDf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


paws  hair  tale  diameter sexe
momy   100.0   5.0  20.0      80.0    f
baby    50.0   2.4   9.0      40.0    f
dady   110.0   5.0  22.0      83.0    m
son     80.0   4.0  15.0      65.0    m
giant  200.0   8.0  30.0     100.0    m

In [0]:
# other things
# to count the number of rows:
x = len(newDf)
# to count number of columns
y = len(newDf.columns)
print("the number of rows: {}\nthe number of columns: {}".format(x,y))

# to get the distincted values of a column
print("the length of the tales are: {}".format(newDf.tale.unique()))

the number of rows: 5
the number of columns: 5
the length of the tales are: [20.  9. 22. 15. 30.]


#importing dataset

this is how to import a data set from your PC
the dataset has to be in the 'csv' format (comma separated values)

In [0]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [0]:
import io
train = pd.read_csv(io.BytesIO(uploaded['train.csv']))
print(len(trains))

398
