importing the numpy library:

In [0]:
import numpy as np

trying numpy's arrays:

In [0]:
# an array of ints:
a = np.array([1,2,3])
print(a)
# an array of floats(we define the type with the dtype argument without introducing float numbers)
af = np.array([1,2,3],dtype="float32")
print(af)
print(type(af), af.shape)
mat = np.array([[1,2,3],[4,5,6]])
print(type(mat),mat.shape)

[1 2 3]
[1. 2. 3.]
<class 'numpy.ndarray'> (3,)
<class 'numpy.ndarray'> (2, 3)
6


so all shapes in numpy are considered as arrays (numpy.ndarray).

In [0]:
mat2=np.array([range(i, i + 3) for i in [2, 4, 6]])
print(mat2)
print("\n",type(mat2),mat2.shape)

[[2 3 4]
 [4 5 6]
 [6 7 8]]

 <class 'numpy.ndarray'> (3, 3)


same thing, an array.

numpy is able to fill arrays with values of our choice (without introducing the values one by one):

In [0]:
# an array full of zeros np.zeros(shape,dtype)
z = np.zeros((2,5),dtype="int8")

In [0]:
# an array full of ones np.ones(shape,dtype)
o = np.ones((2,),dtype="float32")

In [0]:
# an array full of a specific value x np.full(shape,x,dtype)
x = np.full((2,3,4),3.14,dtype="float32")

In [0]:
# an array full of values between a range np.arange(start,stop,step=1)
r = np.arange(10,50,10)

In [0]:
# an array full of random values np.random.random(shape,dtype)
rand = np.random.random((2,2))
# np.random.randint(shape)
# np.random.ranf(shape)
randint = np.random.randint(1,10,size=(3,3))

In [0]:
# identity matrix with a SxS shape np.eye(S)
eye = np.eye(3)

In [13]:
print (z,o,x,r,rand,eye,randint,sep="\n*********\n")

[[0 0 0 0 0]
 [0 0 0 0 0]]
*********
[1. 1.]
*********
[[[3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]]

 [[3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]]]
*********
[10 20 30 40]
*********
[[0.73889598 0.07367266]
 [0.91659082 0.97015154]]
*********
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*********
[[5 6 6]
 [3 5 8]
 [5 3 6]]


some array properties:

In [0]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([9,9,9])
print("x = ",x, end="\n**********\n")
print("y = ",y, end="\n**********\n")
print("x's dimension: {} || y's dimension: {}".format(x.ndim,y.ndim))
print("x's shape: {} || y's shape: {}".format(x.shape,y.shape))
print("x's size: {} || y's size: {}".format(x.size,y.size))
print("x's type: {} || y's type: {}".format(type(x),type(y)))

x =  [[1 2 3]
 [4 5 6]]
**********
y =  [9 9 9]
**********
x's dimension: 2 || y's dimension: 1
x's shape: (2, 3) || y's shape: (3,)
x's size: 6 || y's size: 3
x's type: <class 'numpy.ndarray'> || y's type: <class 'numpy.ndarray'>


some array operations:

In [0]:
# concatenation np.concatenate([array1,array2])
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate([a,b])
print("c = {}".format(c))

#vertical stacking, stack x on y : np.vstack([x,y]) (same colomn shape required)
grid = np.array([[1,1,1],
                 [2,2,2]])
z = np.array([3,3,3])
c = np.vstack([grid,z,a])
print("new c = \n{}".format(c))

#horizontal stacking, concatenate x to y np.hstack([y,x]) (same ligne shape required)
grid2 = np.array([[3,3,3],
                  [4,4,4]])
c = np.hstack([grid,grid2])
print("new new c = \n{}".format(c))

c = [1 2 3 4 5 6]
new c = 
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [1 2 3]]
new new c = 
[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]


In [14]:
# slicing
x = np.array([[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19]])
print(x[:,2:-2])

[[ 2  3  4  5  6  7]
 [12 13 14 15 16 17]]


**Broadcasting**

In [69]:

x = np.arange(5) #[0,1,2,3,4]
print("x + 5 = {}".format(x+5))
print("x * 2 = {}".format(x*2))
print("x / 2 = {}".format(x/2))
print("x // 2 = {}".format(x//2))
print("x % 2 = {}".format(x%2))
print("(x+5) + (x**2) = {}".format((x+5) + (x**2)))

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

print("x + v = \n{}".format(x+v))

x + 5 = [5 6 7 8 9]
x * 2 = [0 2 4 6 8]
x / 2 = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]
x % 2 = [0 1 0 1 0]
(x+5) + (x**2) = [ 5  7 11 17 25]
x + v = 
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [23]:
# some functions
x = [-2, -1, 1, 2]
print("abs: {}".format(np.abs(x)))
print("exp: {}".format(np.exp(x)))
print("log: {}".format(np.log(np.abs(x))))

abs: [2 1 1 2]
exp: [0.13533528 0.36787944 2.71828183 7.3890561 ]
log: [0.69314718 0.         0.         0.69314718]


In [28]:
# inverse matrix
mat = np.random.randint(1,15,(4,4))
print(mat,end="\n**********\n")
inv_mat = (1.0/mat)
print(inv_mat)

[[ 4 12  5 11]
 [ 3 14 14  8]
 [ 4  3  8 10]
 [ 2 14 13  1]]
**********
[[0.25       0.08333333 0.2        0.09090909]
 [0.33333333 0.07142857 0.07142857 0.125     ]
 [0.25       0.33333333 0.125      0.1       ]
 [0.5        0.07142857 0.07692308 1.        ]]


We an also define our functions:

In [51]:
def fun(x):
  return x+x.ndim

mat = np.full((2,2),2)
print(fun(mat))

[[4 4]
 [4 4]]


**Boolean indexing**

In [41]:
mat = np.random.randint(0,16,(4,4))
bool_index = (mat%2==0) #return an array of booleans with the same shape as mat's
print(mat)
print()
print(bool_index)

[[10 15  9  3]
 [11  2  8 14]
 [14  9  5  2]
 [ 3  2  4 11]]

[[ True False False False]
 [False  True  True  True]
 [ True False False  True]
 [False  True  True False]]


In [42]:
mat_pair = mat[bool_index] # mat[bool_index] will return a array of elements that validate the condition with ndim==1
print(mat_pair) 

[10  2  8 14 14  2  2  4]


In [44]:
print(mat_pair[mat_pair>=4]) # you can add directly the condition without using a variable
print(np.where(mat_pair>=4)) # or use the function np.where

[10  8 14 14  4]
(array([0, 2, 3, 4, 7]),)


**Agregation**:

In [56]:
five = np.full((1,5),1) 
five_scale = np.sum(five)
print(five_scale)
nine = np.full((3,3),1)
nine_scale = np.sum(nine)
print(nine_scale) # the function np.sum will sum all the values in the array elementwise

5
9
[3 3 3]


In [57]:
mat2 = np.array([[1,1,1],
                 [2,2,2],
                 [3,3,3]]) 
print(mat2.sum(axis=0)) # to sum the elements ligne by ligne, the shape will be equal to the number of colomns
print(mat2.sum(axis=1)) # to sum the elements column by column, the shape will be equal to the number of lignes

[6 6 6]
[3 6 9]


**Statistics functions**:


1.   `np.std()`: to calculate the standart deviation
2.   `np.argmin()`: return the index of the minimum
3.   `np.argmax()`: return the index of the maximum
4.   `np.percentile()`: to calculate the statistics on the elements 



In [68]:
mat = np.random.random((5,5))
print(mat)
print(np.argmin(mat))
print(np.argmax(mat))
print(np.std(mat))

[[0.12751715 0.65442069 0.86076538 0.47873406 0.37814743]
 [0.62110399 0.76844711 0.89260685 0.59132629 0.43934275]
 [0.63787844 0.99727578 0.88724368 0.79814502 0.11725742]
 [0.82568164 0.52890998 0.61675195 0.40522874 0.5623576 ]
 [0.20988811 0.36593987 0.21966703 0.6369223  0.97463783]]
14
11
0.2525835231206826


**vector product nad transpos**:

In [73]:
# vector product
a = np.array([1,2,3])  # x1x2 + y1y2 + z1z2.....
b = np.array([4,5,6])
print(a.dot(b))

# tranpose
d = np.array([9,9,9])
c = np.array([8,8,8])
print(np.vstack([a,b,c,d]).T)

32
[[1 4 8 9]
 [2 5 8 9]
 [3 6 8 9]]


**Reshaping**:

In [76]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
b = a.reshape(1,6) # to rechape an array we must have x0 * y0 == x1 * y2
print(b,"\n",b.shape)

(2, 3)
[[1 2 3 4 5 6]] 
 (1, 6)
